services:
  brokerserver:
    container_name: broker_container
    image: "rabbitmq:3-management-alpine"
    hostname: "my-rabbit"
    volumes:
      - ./config/rabbitmq/default-definitions.conf:/etc/rabbitmq/conf.d/rabbitmq.conf:ro
      - ./config/rabbitmq/mqtt.conf:/etc/rabbitmq/conf.d/20-mqtt.conf:ro
      - ./config/rabbitmq/enabled-plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./config/rabbitmq/definitions.json:/etc/rabbitmq/conf.d/definitions.json:ro
    ports:
      - "1883:1883"
      - "127.0.0.1:8080:15672"
      - "127.0.0.1:5672:5672"
    networks:
      - backend_space

  stopreasonsstorage:
    container_name: stop_reasons_storage_container
    image: "postgres:16.3"
    user: 1000:1000  # please check this in your linux config with $(id -u):$(id -g)
    env_file:
      - ./config/docker/postgres/docker-env-vars
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ~/local-docker-volumes/pgdbs/stop-reasons-db:/var/lib/postgresql/data/pgdata
      - ./config/docker/postgres/init-scripts:/docker-entrypoint-initdb.d
      - /etc/passwd:/etc/passwd:ro
    networks:
      - backend_space

networks:
  backend_space:
    name: backend_network
    driver: bridge